# Raylib + ImGui Project Starter
# Cross-compiles Linux & Windows from Linux & packages 4 u!
# (c) Softwave 2026 — MIT License
#
# Usage:
#   1. Set Project, Version, and Assets variables
#   2. Make sure your code files are there
#   3. `make` for Linux, `make windows` for Windows, `make zip` for both
#
#   Needed for Linux:   g++, raylib & libraylib.so, GL/X11 dev libs
#   Needed for Windows cross-building: x86_64-w64-mingw32-g++, a Windows-built libraylib.a


# Basic project settings
PROJECT  := Waves
VERSION  := 0.4

BUILD_CONFIG := build_config.h

# Your source files (everything that isn't ImGui/rlImGui)
APP_SRCS := main.cpp

# Stuff to put in dist packages (shaders, fonts, sounds, configs, docs etc.)
ASSETS   := \
	DM.ttf \
	wave.fs imgui.ini wave_settings.ini LICENSE README.md

# NOTE: You may have to change this to find YOUR SPECIFIC libraylib.so library
RAYLIB_SO := /usr/lib64/libraylib.so.550

# Flags & stuff
CXX          := g++
WIN_CXX      := x86_64-w64-mingw32-g++

COMMON_FLAGS := -std=c++17 -Wall -Wextra

CXXFLAGS       = $(COMMON_FLAGS) -O2
DEBUG_CXXFLAGS = $(COMMON_FLAGS) -O0 -g -DDEBUG

WIN_CXXFLAGS   = $(COMMON_FLAGS) -O2 -static

# Linker
# Linux -- linking with lib in libs
LDFLAGS     := -L./libs -lraylib -lGL -lm -lpthread -ldl -lrt -lX11 \
               -Wl,-rpath,'$$ORIGIN/libs'

# Windows: we statically link everything
WIN_LDFLAGS := -lraylib -lopengl32 -lgdi32 -lwinmm \
               -static-libgcc -static-libstdc++

# ImGui sources
IMGUI_SRCS := imgui.cpp imgui_draw.cpp imgui_demo.cpp imgui_tables.cpp imgui_widgets.cpp \
              rlImGui.cpp

ALL_SRCS   := $(APP_SRCS) $(IMGUI_SRCS)

TARGET     := $(PROJECT)
WIN_TARGET := $(PROJECT).exe

OBJS       := $(ALL_SRCS:.cpp=.o)
WIN_OBJS   := $(ALL_SRCS:.cpp=_win.o)
DBG_OBJS   := $(ALL_SRCS:.cpp=_dbg.o)

DIST_LINUX := dist/$(PROJECT)_Linux_v$(VERSION)
DIST_WIN   := dist/$(PROJECT)_Windows_v$(VERSION)

# Targets
.PHONY: all windows debug clean run dist zip install-deps help

all: $(TARGET)

$(TARGET): $(BUILD_CONFIG) $(OBJS)
	$(CXX) $(OBJS) -o $@ $(LDFLAGS)

$(BUILD_CONFIG): Makefile
	@echo "// Auto-generated by Makefile. Do not edit." > $(BUILD_CONFIG)
	@echo "#pragma once" >> $(BUILD_CONFIG)
	@echo "#define APP_PROJECT \"$(PROJECT)\"" >> $(BUILD_CONFIG)
	@echo "#define APP_VERSION \"$(VERSION)\"" >> $(BUILD_CONFIG)

%.o: %.cpp $(BUILD_CONFIG)
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Debug
debug: CXXFLAGS = $(DEBUG_CXXFLAGS)
debug: $(PROJECT)_debug

$(PROJECT)_debug: $(BUILD_CONFIG) $(DBG_OBJS)
	$(CXX) $(DBG_OBJS) -o $@ $(LDFLAGS)

%_dbg.o: %.cpp $(BUILD_CONFIG)
	$(CXX) $(DEBUG_CXXFLAGS) -c $< -o $@

# Cross-compile from Linux -> Windows
windows: $(WIN_TARGET)

$(WIN_TARGET): $(BUILD_CONFIG) $(WIN_OBJS)
	$(WIN_CXX) $(WIN_CXXFLAGS) -o $@ $(WIN_OBJS) $(WIN_LDFLAGS)

%_win.o: %.cpp $(BUILD_CONFIG)
	$(WIN_CXX) $(WIN_CXXFLAGS) -c $< -o $@

# Package for publishing
dist: $(TARGET) $(WIN_TARGET)
	@echo "=== Packaging $(PROJECT) v$(VERSION) ==="
	mkdir -p $(DIST_LINUX)/libs $(DIST_WIN)
	mkdir -p $(DIST_LINUX)/screens $(DIST_WIN)/screens
	cp $(TARGET)     $(ASSETS) $(DIST_LINUX)/
	cp $(WIN_TARGET) $(ASSETS) $(DIST_WIN)/
ifneq ($(wildcard $(RAYLIB_SO)),)
	cp $(RAYLIB_SO) $(DIST_LINUX)/libs/
else
	@echo "WARNING: $(RAYLIB_SO) not found — Linux dist won't have bundled raylib"
endif
	@echo "Done: $(DIST_LINUX)/ and $(DIST_WIN)/"

zip: dist
	@mkdir -p dist
	cd dist && zip -r $(PROJECT)_Linux_v$(VERSION).zip  $(notdir $(DIST_LINUX))/
	cd dist && zip -r $(PROJECT)_Windows_v$(VERSION).zip $(notdir $(DIST_WIN))/
	@echo "Created dist/$(PROJECT)_Linux_v$(VERSION).zip"
	@echo "Created dist/$(PROJECT)_Windows_v$(VERSION).zip"

# Nice to have
run: $(TARGET)
	./$(TARGET)

clean:
	rm -f *.o screenshot_*.png $(TARGET) $(WIN_TARGET) $(PROJECT)_debug $(BUILD_CONFIG)
	rm -rf dist/

# Test to see if findable
check-deps:
	@echo -n "g++:           " && which $(CXX)      || echo "MISSING"
	@echo -n "mingw-w64:     " && which $(WIN_CXX)  || echo "MISSING"
	@echo -n "raylib.so:     " && ls $(RAYLIB_SO)    || echo "MISSING"
	@echo -n "raylib header: " && ls /usr/include/raylib.h 2>/dev/null \
	                            || echo "not at default path (may still be fine)"

help:
	@echo ""
	@echo "  $(PROJECT) v$(VERSION) — Raylib + ImGui Build System"
	@echo ""
	@echo "  make              Build for Linux (default)"
	@echo "  make windows      Cross-compile for Windows"
	@echo "  make debug        Linux debug build (-O0, -g, -DDEBUG)"
	@echo "  make run          Build & run Linux version"
	@echo "  make dist         Package Linux + Windows into dist/"
	@echo "  make zip          dist + create .zip archives"
	@echo "  make clean        Remove all build artifacts"
	@echo "  make check-deps   Verify toolchain is available"
	@echo "  make help         This message"
	@echo ""
